---

- template:
    src: core-site.xml.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/core-site.xml
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644

- template:
    src: yarn-site.xml.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/yarn-site.xml
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644

- template:
    src: mapred-site.xml.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/mapred-site.xml
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644


- template:
    src: hdfs-site.xml.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/hdfs-site.xml
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644


