---


- name: download hadoop
  get_url:
    url: "{{ hadoop_url }}"
    dest: /home/{{ hadoop_user }}/
    checksum: sha256:"{{ hadoop_sha256 }}"

- file: 
    path: /home/{{ hadoop_user }}/hadoop-{{ hadoop_version }}.tar.gz
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    mode: 0644

- file:
    path: /u02/
    state: directory
    mode: 0755
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"

- unarchive:
    src: /home/{{ hadoop_user }}/hadoop-{{ hadoop_version }}.tar.gz
    dest: "/u02/"
    copy: no

- file:
    path: /u02/hadoop-{{ hadoop_version }}
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    recurse: yes


- template:
    src: core-site.xml.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/core-site.xml
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644

- template:
    src: yarn-site.xml.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/yarn-site.xml
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644

- template:
    src: mapred-site.xml.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/mapred-site.xml
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644

- template:
    src: hdfs-site.xml.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/hdfs-site.xml
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644

