---

- name: Install main node env
  hosts: main_node 
  sudo: yes

  roles:
#    - main_node

- name: Install env
  hosts: hadoop
  sudo: yes
 

  roles:
    - thirdparty
    - hadoop
  environment:
    http_proxy: http://{{ proxy_server }}:3128
    https_proxy: http://{{ proxy_server }}:3128


- name: Install hadoop
  hosts: hadoop
  sudo: yes


  roles:
    - hadoop_slave
    - hadoop_master
