---

- name: Install main node env
  hosts: main_node 
  sudo: yes

  roles:
    - main_node


- name: Install hadoop env
  hosts: hadoop
  sudo: yes
 

  roles:
    - thirdparty
#    - java
#    - hadoop
#    - hbase
  environment:
    http_proxy: http://{{ proxy_server }}:3128
    https_proxy: http://{{ proxy_server }}:3128

