---

- template:
    src: core-site.xml.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/core-site.xml
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644

- template:
    src: yarn-site.xml.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/yarn-site.xml
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644

- template:
    src: mapred-site.xml.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/mapred-site.xml
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644

- template:
    src: hdfs-site.xml.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/hdfs-site.xml
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644

- name: added master
  shell: echo "hadoop1" > /u02/hadoop-{{ hadoop_version }}/etc/hadoop/masters

- file:
    path: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/masters
    state: file
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"


- template:
    src: slaves.template
    dest: /u02/hadoop-{{ hadoop_version }}/etc/hadoop/slaves
    group: "{{ hadoop_group }}"
    owner:  "{{ hadoop_user }}"
    mode: 0644


- name: format hdfs 
  shell: source ~/.bashrc && /u02/hadoop-{{ hadoop_version }}/bin/hdfs namenode -format
  become: yes
  become_user: "{{ hadoop_user }}"

- name: run hadoop
  shell: source ~/.bashrc && /u02/hadoop-{{ hadoop_version }}/sbin/start-all.sh
  become: yes
  become_user: "{{ hadoop_user }}"
